### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by jpupper** [sdao/fur-demo#1]
Hello ! Sorry to bother you, 

But i don´t understand how to compile the proyect.

- I´ve downloaded the zip.
- i´ve open the .sln file. 
-Click on compile. 

Not working. 

gettin this : `Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp_glfwWindowShouldClose	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol png_create_info_struct	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_create_read_struct	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_destroy_read_struct	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_bit_depth	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_channels	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_color_type	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_image_height	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_image_width	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_io_ptr	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_get_valid	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_read_image	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_read_info	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_set_longjmp_fn	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_set_palette_to_rgb	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_set_read_fn	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_set_sig_bytes	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_set_strip_16	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_set_tRNS_to_alpha	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol png_sig_cmp	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Texture.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwCreateWindow	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwGetFramebufferSize	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwGetTime	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwInit	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwMakeContextCurrent	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwPollEvents	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwSwapBuffers	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwTerminate	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
Error	LNK2001	unresolved external symbol __imp_glfwWindowHint	fur-demo	C:\WORKSPACE\of_v0.9.8_vs_release\apps\myApps\fur-demo-master\Canvas.obj	1	
`
Could you please inform me how to compile the proyect?

**Comment by sdao** [comment]
Hi, I just tried downloading it (I haven't touched this in a few years!) and compiling in Visual Studio Community 2015 (x64) and it seems to work OK. I'm not sure about VS2017, but I would be surprised if the version difference was causing the linker errors.
Did you make sure that the NuGet packages were downloaded properly? You'll want to make sure that the correct versions are installed (don't update the NuGet packages, just "restore" them).

**Comment by jpupper** [comment]
I was not aware that NuGet packages, what are the specific NuGet packages need it for this proyect?

**Comment by sdao** [comment]
Hi, the NuGet packages are already defined in the solution.
Please see the NuGet documentation on how to restore the NuGet package dependencies: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore
If you have already restored but it doesn't seem to work, you may want to reinstall packages: https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages
As I mention before, make sure you _do not update_ the packages because I can't guarantee that it will work with newer versions of the libraries.
